server:
  port: 8080

remote:
  account-service:
    base-url: ${ACCOUNT_SERVICE_BASE_URL:http://localhost:8081}
  income-service:
    base-url: ${INCOME_SERVICE_BASE_URL:http://localhost:8082}
  orders-service:
    base-url: ${ORDERS_SERVICE_BASE_URL:http://localhost:8083}
