version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db-init:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

  filestorage-service:
    build:
      context: ./FileStorageService
    container_name: filestorage_service
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/filestorage_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      FILESTORAGE_PATH: /app/storage
    volumes:
      - ./storage:/app/storage
    ports:
      - "8081:8080"

  fileanalysis-service:
    build:
      context: ./FileAnalysisService
    container_name: fileanalysis_service
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/fileanalysis_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      FILESTORAGE_SERVICE_URL: http://filestorage-service:8080
    ports:
      - "8082:8080"

  gateway-service:
    build:
      context: ./GatewayService
    container_name: gateway_service
    environment:
      STORAGE_SERVICE_BASE_URL: http://filestorage-service:8080
      ANALYSIS_SERVICE_BASE_URL: http://fileanalysis-service:8080
    ports:
      - "8080:8080"

volumes:
  postgres_data:
